### PR TITLE
Modified method of checking if object is an array

### PR DESCRIPTION
**Pull request by TidbitSoftware**
Supposedly this is the fastest way to check if an object is an array.

### CODE REVIEW

**Comment by TidbitSoftware** [comment]
Crap: I need to make a new commit as I forgot the element addressing on the second check.

**Comment by TidbitSoftware** [comment]
I really don't know why it's not passing the unit testing at this point.

**Comment by lukebro** [comment]
You need to safely deconstruct the property `(item && item.constructor)`

**Comment by TidbitSoftware** [comment]
Of course I totally missed the test script right there in the repo. This is why I shouldn't be allowed to commit / make pull requests late night.

**Comment by lukebro** [comment]
@TidbitSoftware nice, thank you!

**Pull request merged**
